- hosts: "{{ host | default('dev') }}"

  become: yes
  become_method: sudo
  become_user: root

  tasks:

    - name: create destination directory
      file:
        path: /usr/local/ganache
        state: directory

    - name: upload files
      synchronize:
        src: ./
        dest: /usr/local/ganache
        delete: yes
        recursive: yes
        rsync_opts:
          - "--verbose"
          - "--include=./***"
          - "--exclude=node_modules"

    - name: remove docker image
      docker_image:
        path: /usr/local/ganache
        name: horizon-games/ganache
        state: absent
        force: yes

    - name: build docker image
      docker_image:
        rm: yes
        path: /usr/local/ganache
        name: horizon-games/ganache
        state: present
        force: yes
